version: "3.7"
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: on-failure
  postgres:
    image: postgres:13
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      # - "./initdb.d:/docker-entrypoint-initdb.d"
      - musicapidata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: musicapi
      POSTGRES_USER: developer
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
  migration:
    build:
      context: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "postgres:5432",
        "--",
        "npm",
        "run",
        "migrate",
        "up"
      ]
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - .env
volumes:
  musicapidata: